I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter_1.rpy", line 3669, in script call
    call lanaAcpt1 from _call_lanaAcpt1
  File "game/chapter_1.rpy", line 3731, in script call
    call lanaAcpt2 from _call_lanaAcpt2
  File "game/chapter_1.rpy", line 4133, in script call
    call ACCEPTEDLAW from _call_ACCEPTEDLAW
  File "game/chapter_1.rpy", line 1398, in script call
    call natsugropaccpt from _call_natsugropaccpt
  File "game/chapter_2.rpy", line 9306, in script
    Natusko "N-no! , I mean it's just because it's cold."
Exception: Sayer 'Natusko' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter_1.rpy", line 3669, in script call
    call lanaAcpt1 from _call_lanaAcpt1
  File "game/chapter_1.rpy", line 3731, in script call
    call lanaAcpt2 from _call_lanaAcpt2
  File "game/chapter_1.rpy", line 4133, in script call
    call ACCEPTEDLAW from _call_ACCEPTEDLAW
  File "game/chapter_1.rpy", line 1398, in script call
    call natsugropaccpt from _call_natsugropaccpt
  File "game/chapter_2.rpy", line 9306, in script
    Natusko "N-no! , I mean it's just because it's cold."
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\DESKTOP\Downloads\Programs\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Natusko' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
 0.4
Mon Jun 12 03:12:12 2023
