I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter_2.rpy", line 7183, in script
    jump chap_2_scene_40
ScriptError: could not find label 'chap_2_scene_40'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter_2.rpy", line 7183, in script
    jump chap_2_scene_40
  File "renpy/ast.py", line 1711, in execute
    rv = renpy.game.script.lookup(target)
  File "renpy/script.py", line 910, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'chap_2_scene_40'.

Windows-10-10.0.19041
Ren'Py 7.4.5.1648
 0.3
Thu May 18 18:24:43 2023
